services:
  lep-db:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
    networks:
      - app-network

  lep-django:
    build:
      context: ./ml_backend
      dockerfile: Dockerfile
    container_name: lep-django
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput --clear &&
             python manage.py initadmin &&
             gunicorn ml_backend.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    working_dir: /app
    volumes:
      - ./ml_backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    env_file: .env
    depends_on:
      - lep-db
      - redis
      - rabbitmq
      - minio
    restart: always
    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - app-network


  celery:
    container_name: celery_worker
    build:
      context: ./ml_backend
      dockerfile: Dockerfile
    # параметры оптимизации
    command: >
      celery -A ml_backend worker 
      --loglevel=INFO 
      --concurrency=2 
      --prefetch-multiplier=1 
      --max-tasks-per-child=50
    volumes:
      - ./ml_backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file: .env
    depends_on:
      - lep-django
      - rabbitmq
      - redis
      - minio
    restart: always
    networks:
      - app-network
    # Ограничение ресурсов (опционально, но рекомендуется)
    deploy:
      resources:
        limits:
          cpus: '6.0'      # Максимум 2 CPU
          memory: 10G       # Максимум 4GB RAM
        reservations:
          cpus: '1.0'      # Минимум 1 CPU
          memory: 2G       # Минимум 2GB RAM

  minio:
    image: minio/minio
    container_name: minio
    env_file: .env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

  redis:
    container_name: redis_cache
    image: redis:7-alpine
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - app-network

  lep-nginx:
    image: nginx:1.27-alpine
    container_name: lep-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - lep-django
      - minio
    restart: always
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:
  media_volume:
  rabbitmq_data:
  minio_data:
  redis_data:

networks:
  app-network:
    driver: bridge